groups: 
  - name: Wrong MTU on hana01
    rules:
      # To test the alert simply do:
      # docker exec -it hana01 /bin/bash
      # ip link set mtu 9000 dev lo
      # Default is: 65536
      - alert: mtu
        expr: node_network_mtu_bytes{device="lo"} == 9000
        for: 1m
        labels:
        annotations:
          title: MTU has been changed
          description:  MTU has been changed to 9000




